### PR TITLE
feat: noticket - Fix deprecations in React 15.5.0

### PR DESCRIPTION
**Pull request by AaronKalair**
Hi,

We're using this library and after upgrading to React 15.5.0 noticed some warnings about deprecations so this PR fixes those issues.

Thanks

### CODE REVIEW

**Comment by pughpugh** [comment]
Thanks Aaron, that's very kind of you, I will take a look.

**Comment by AaronKalair** [comment]
No problem 👍 . I have just realised that in it's current state this would be a breaking change (the dependency on React 15.5) so maybe it needs a major version bump?

It may also be possible to support React 15.5 and older versions, I haven't had a chance to look into it though :)

**Comment by bradbirnbaum** [comment]
Any chance we can accept this pull?

**Comment by pughpugh** [comment]
Yup, well overdue. Done. Thanks all.

**Pull request merged**
